In [1]:
import os
import sys

from matplotlib import pyplot as plt
import pandas as pd
import seaborn as sns
from ydata_profiling import ProfileReport

sys.path.insert(0, os.path.abspath(os.path.join(os.getcwd(), "..")))

from src.environment import CONFIGS_DIR, METRICS_DIR, REPORTS_DIR, ROOT

CLEAN_RUN = False
SAVE_FIGS = True
FIGURES_FORMAT = "pdf"

sns.set_theme(palette="colorblind", color_codes=True)

plt.style.use(CONFIGS_DIR / "figures.mplstyle")

%matplotlib inline

## Load data

In [2]:
INDEPENDENT_VARIABLES = [
    "training environment",
    "architecture",
    "dataset",
    "batch size",
    "image size",
    "total ram (GB)",
]
RELEVANT_METRICS = [
    "run_id",
    "start time",
    "training duration (h)",
    "return code",
    "gpu usage (%)",
    "average gpu power (W)",
    "gpu energy (MJ)",
    "max power limit (W)",
    "ram energy (MJ)",
    "energy (MJ)",
    "average temperature (Celsius)",
    "GFLOPs",
    "trained epochs",
    "measured epochs",
    "total seen images",
]

In [3]:
aggregated_metrics = pd.read_parquet(
    METRICS_DIR / "processed" / "dl-training-energy-consumption-dataset.gzip"
).sort_values(by=["start time"])

In [4]:
# Remove runs that did not finish successfully
original_number_of_runs = len(aggregated_metrics)
aggregated_metrics = aggregated_metrics.loc[aggregated_metrics["return code"] == 0]
print(f"Inital number of runs: {original_number_of_runs}")
print(f"Removed {original_number_of_runs - len(aggregated_metrics)} runs")
print(f"Number of runs: {len(aggregated_metrics)}")

Inital number of runs: 1630
Removed 107 runs
Number of runs: 1523

## Automatic EDA with Ydata Profiling

In [ ]:
if not os.path.exists(REPORTS_DIR / "dl-training-energy-consumption-dataset.html") or CLEAN_RUN:
    type_schema = {
        "training environment": "categorical",
        "architecture": "categorical",
        "dataset": "categorical",
        "run": "numeric",
        "run_id": "categorical",
        "start time": "datetime",
        "training duration (h)": "numeric",
        "gpu model": "categorical",
        "gpu working time (h)": "numeric",
        "gpu usage (%)": "numeric",
        "gpu memory working time (h)": "numeric",
        "gpu memory usage": "numeric",
        "gpu average memory used (MB)": "numeric",
        "gpu memory used std (MB)": "numeric",
        "total power (W)": "numeric",
        "average gpu power (W)": "numeric",
        "gpu power std (W)": "numeric",
        "max power limit (W)": "numeric",
        "average temperature (Celsius)": "numeric",
        "temperature std (Celsius)": "numeric",
        "average cpu usage (%)": "numeric",
        "cpu usage std (%)": "numeric",
        "average ram used (MB)": "numeric",
        "ram used std (MB)": "numeric",
        "average ram power (W)": "numeric",
        "ram power std (W)": "numeric",
        "total ram (GB)": "numeric",
        "gpu energy (MJ)": "numeric",
        "ram energy (MJ)": "numeric",
        "energy (MJ)": "numeric",
        "emissions (gCO2e)": "numeric",
        "mlflow run id": "categorical",
        "training size": "numeric",
        "validation size": "numeric",
        "batch size": "numeric",
        "image size": "categorical",
        "trained epochs": "numeric",
        "GFLOPs": "numeric",
        "accuracy": "numeric",
        "AUC": "numeric",
        "split number": "numeric",
        "total seen images": "numeric",
        "precision": "numeric",
        "recall": "numeric",
        "f1-score": "numeric",
        "return code": "numeric",
    }
    profile = ProfileReport(
        aggregated_metrics,
        title="Deep Learning Training Energy Consumption Dataset",
        type_schema=type_schema,
        explorative=True,
    )
    profile.to_file(ROOT / "reports" / "dl-training-energy-consumption-dataset.html")

## Data Cleaning

In [6]:
TRAIN_STRATEGIES = aggregated_metrics["training environment"].unique()
MARKERS = {
    "MobileNet V2": "o",
    "NASNet Mobile": "v",
    "Xception": "^",
    "ResNet50": "X",
    "VGG16": "P",
}
COLORS = {environment: color for environment, color in zip(TRAIN_STRATEGIES, ["b", "orange", "g"])}
ARCHITECTURE_LABELS = ["MobileNet\nV2", "NASNet\nMobile", "ResNet50", "VGG16", "Xception"]

In [7]:
analysis_df = aggregated_metrics[INDEPENDENT_VARIABLES + RELEVANT_METRICS].copy()

Look for missing values

In [8]:
analysis_df.isna().any(axis=0)

training environment             False
architecture                     False
dataset                          False
batch size                       False
image size                       False
total ram (GB)                    True
run_id                           False
start time                       False
training duration (h)            False
return code                      False
gpu usage (%)                    False
average gpu power (W)            False
gpu energy (MJ)                  False
max power limit (W)              False
ram energy (MJ)                   True
energy (MJ)                       True
average temperature (Celsius)    False
GFLOPs                            True
trained epochs                   False
measured epochs                  False
total seen images                False
dtype: bool

The only columns with missing values are the ones related to the RAM and the GFLOPs.

Since all runs have the same total RAM and GFLOPs for a given setting we just propagate the values to those with NaN.

In [9]:
analysis_df.loc[:, "total ram (GB)"] = (
    analysis_df.groupby(INDEPENDENT_VARIABLES[:-1], as_index=False)["total ram (GB)"].bfill().ffill()
)

In [10]:
analysis_df.loc[:, "GFLOPs"] = analysis_df.groupby("architecture", as_index=False)["GFLOPs"].bfill().ffill()

In [11]:
analysis_df.groupby(INDEPENDENT_VARIABLES, dropna=False).agg({"run_id": "count", "ram energy (MJ)": "count"})

                                                                                             run_id  \
training environment architecture  dataset             batch size image size total ram (GB)
Desktop ML Engineer  inception_v3  caltech101          32         (128, 128) 32.0                32
                                                                  (224, 224) 32.0                32
                                                                  (75, 75)   32.0                31
                                                       64         (128, 128) 32.0                32
                                                                  (224, 224) 32.0                30
                                                                  (75, 75)   32.0                31
                                                       256        (128, 128) 32.0                30
                                                                  (224, 224) 32.0                30
                                                                  (75, 75)   32.0                59
                                   stanford_dogs       32         (128, 128) 32.0                31
                                                                  (224, 224) 32.0                30
                                                                  (75, 75)   32.0                30
                                                       64         (128, 128) 32.0                30
                                                                  (224, 224) 32.0                30
                                                                  (75, 75)   32.0                31
                                                       256        (128, 128) 32.0                30
                                                                  (224, 224) 32.0                31
                                                                  (75, 75)   32.0                31
                     mobilenet_v2  chesslive-occupancy 32         (128, 128) 32.0                37
                     nasnet_mobile chesslive-occupancy 32         (128, 128) 32.0                30
                     resnet50      chesslive-occupancy 32         (128, 128) 32.0                30
                     vgg16         chesslive-occupancy 32         (128, 128) 32.0                32
                     xception      chesslive-occupancy 32         (128, 128) 32.0                30
Desktop Normal User  mobilenet_v2  chesslive-occupancy 32         (128, 128) 32.0                30
                     nasnet_mobile chesslive-occupancy 32         (128, 128) 32.0                30
Server               inception_v3  caltech101          32         (128, 128) 16.0                30
                                                                  (224, 224) 16.0                30
                                                                  (75, 75)   16.0                30
                                                       64         (128, 128) 16.0                30
                                                                  (224, 224) 16.0                30
                                                                  (75, 75)   16.0                30
                                                       256        (128, 128) 16.0                30
                                                                  (224, 224) 16.0                30
                                                                  (75, 75)   16.0                60
                                   stanford_dogs       32         (128, 128) 16.0                30
                                                                  (224, 224) 16.0                 5
                                                                  (75, 75)   16.0                30
                                                       64         (128, 128) 16.0                30
                                                                  (75, 75)   16.0                30
                                                       256        (128, 128) 8.0                 30
                                                                             16.0                30
                                                                             24.0                30
                                                                             32.0                30
                                                                  (75, 75)   16.0                30
                     mobilenet_v2  chesslive-occupancy 32         (128, 128) 16.0                30
                     nasnet_mobile chesslive-occupancy 32         (128, 128) 16.0                28
                     resnet50      chesslive-occupancy 32         (128, 128) 16.0                30
                     vgg16         chesslive-occupancy 32         (128, 128) 16.0                30
                     xception      chesslive-occupancy 32         (128, 128) 16.0                30

                                                                                             ram energy (MJ)
training environment architecture  dataset             batch size image size total ram (GB)
Desktop ML Engineer  inception_v3  caltech101          32         (128, 128) 32.0                         32
                                                                  (224, 224) 32.0                         32
                                                                  (75, 75)   32.0                         31
                                                       64         (128, 128) 32.0                         32
                                                                  (224, 224) 32.0                         30
                                                                  (75, 75)   32.0                         31
                                                       256        (128, 128) 32.0                         30
                                                                  (224, 224) 32.0                         30
                                                                  (75, 75)   32.0                         49
                                   stanford_dogs       32         (128, 128) 32.0                         31
                                                                  (224, 224) 32.0                         30
                                                                  (75, 75)   32.0                         30
                                                       64         (128, 128) 32.0                         30
                                                                  (224, 224) 32.0                         30
                                                                  (75, 75)   32.0                         31
                                                       256        (128, 128) 32.0                         30
                                                                  (224, 224) 32.0                         31
                                                                  (75, 75)   32.0                         31
                     mobilenet_v2  chesslive-occupancy 32         (128, 128) 32.0                         37
                     nasnet_mobile chesslive-occupancy 32         (128, 128) 32.0                         30
                     resnet50      chesslive-occupancy 32         (128, 128) 32.0                         30
                     vgg16         chesslive-occupancy 32         (128, 128) 32.0                         32
                     xception      chesslive-occupancy 32         (128, 128) 32.0                         30
Desktop Normal User  mobilenet_v2  chesslive-occupancy 32         (128, 128) 32.0                         30
                     nasnet_mobile chesslive-occupancy 32         (128, 128) 32.0                         30
Server               inception_v3  caltech101          32         (128, 128) 16.0                         23
                                                                  (224, 224) 16.0                         24
                                                                  (75, 75)   16.0                         25
                                                       64         (128, 128) 16.0                         21
                                                                  (224, 224) 16.0                         22
                                                                  (75, 75)   16.0                         24
                                                       256        (128, 128) 16.0                         22
                                                                  (224, 224) 16.0                         27
                                                                  (75, 75)   16.0                         50
                                   stanford_dogs       32         (128, 128) 16.0                         24
                                                                  (224, 224) 16.0                          3
                                                                  (75, 75)   16.0                         24
                                                       64         (128, 128) 16.0                         25
                                                                  (75, 75)   16.0                         24
                                                       256        (128, 128) 8.0                          30
                                                                             16.0                         21
                                                                             24.0                         30
                                                                             32.0                         30
                                                                  (75, 75)   16.0                         23
                     mobilenet_v2  chesslive-occupancy 32         (128, 128) 16.0                         30
                     nasnet_mobile chesslive-occupancy 32         (128, 128) 16.0                         28
                     resnet50      chesslive-occupancy 32         (128, 128) 16.0                         30
                     vgg16         chesslive-occupancy 32         (128, 128) 16.0                         30
                     xception      chesslive-occupancy 32         (128, 128) 16.0                         30

Since we have no information about the energy consumption of the RAM and the number of runs under this circumstance is not too big, we will remove them from the data.

In [12]:
analysis_df.dropna(inplace=True)
print(f"Number of runs after eliminating NaNs: {len(analysis_df)}")

Number of runs after eliminating NaNs: 1410

Next, we proceed to eliminate those runs that have measurements for less than 20 epochs.
This is to ensure we have enough data of the training process to make a good estimation of the energy consumption.

In [13]:
metrics_df = pd.read_parquet(os.path.join(METRICS_DIR, "interim", "dl-training-profiling-dataset.gzip"))
metrics_df = metrics_df.loc[metrics_df["run_id"].isin(analysis_df["run_id"])]
run_max_epochs = metrics_df.groupby("run_id", as_index=False)["epoch"].max()
run_max_epochs.rename(columns={"epoch": "measured epochs"}, inplace=True)
run_max_epochs["measured epochs"] = run_max_epochs["measured epochs"] + 1

valid_runs = run_max_epochs.query("`measured epochs` >= 20")["run_id"].unique()

print(f"Invalid runs: {len(run_max_epochs) - len(valid_runs)}")

Invalid runs: 5

In [14]:
analysis_df.query("`run_id` in @valid_runs", inplace=True)
print(f"Number of runs after eliminating invalid runs: {len(analysis_df)}")

Number of runs after eliminating invalid runs: 1405

Next, we remove those runs where the epoch duration is below the sampling rate since we will not be able to make a good estimation of the energy consumption.

In [15]:
epoch_energy_df = pd.read_parquet(METRICS_DIR / "interim" / "dl-epoch-energy-consumption-dataset.gzip")
epoch_energy_df["epoch"] = epoch_energy_df["epoch"].astype("int")

In [16]:
tmp = metrics_df.sort_values(["run_id", "timestamp"])
tmp["sampling_period"] = tmp.groupby("run_id", as_index=False)["timestamp"].diff().dt.total_seconds()

In [17]:
tmp = tmp.groupby(["train_environment", "architecture", "dataset", "run_id"], as_index=False)["sampling_period"].min()

epoch_time = epoch_energy_df.groupby("run_id", as_index=False)["duration (s)"].min()

tmp = tmp.merge(epoch_time, on="run_id", how="left")
problematic_runs = tmp.query("`sampling_period` > `duration (s)`")

problematic_runs.groupby("train_environment", as_index=False).agg({"run_id": "count"})

  train_environment  run_id
0           desktop      20
1            server      20

In [18]:
analysys_df = analysis_df.query("`run_id` not in @problematic_runs['run_id']", inplace=True)
print(f"Number of runs after eliminating problematic runs: {len(analysis_df)}")

Number of runs after eliminating problematic runs: 1365

In [19]:
analysis_columns = analysis_df.columns.tolist()
other_metrics = [col for col in aggregated_metrics.columns if col not in analysis_columns]

clean_df = analysis_df.merge(aggregated_metrics[["run_id"] + other_metrics], on="run_id", how="left")

In [20]:
clean_df.to_parquet(METRICS_DIR / "processed" / "clean-dl-training-energy-consumption-dataset.gzip", compression="gzip")

In [21]:
clean_epoch_energy = epoch_energy_df.loc[epoch_energy_df["run_id"].isin(analysis_df["run_id"])]
clean_epoch_energy.to_parquet(
    METRICS_DIR / "processed" / "clean-dl-epoch-energy-consumption-dataset.gzip", compression="gzip"
)